### ISSUE TITLE
Site just loading

### ISSUE THREAD

**Issue by christophrumpel** [fennb/phirehose#101]
Hey,

I am testing some of your examples. I filled in the keys and when I hit the endpoint to this script, the site ist just loading.

The very first time I saw some text (I guess they were tweets) but no site is just loading without any output. That's the same for all the examples that I have tested. Anything I can check? Wheat could be the problem?

Thanks and greets

**Comment by pratiksha2211** [comment]
I have same issue only loading site no any data return 

Can anyone have solution?

**Comment by christophrumpel** [comment]
I found my problem. Seems like there was a problem with my tokens. I created new ones and suddenly it worked. I also don't use it in the browser anymore. Browser can't handle the data. Now it is working great from the console.
