### ISSUE TITLE
Why is Oauthphirehose labeled as internal?

### ISSUE THREAD

**Issue by codedge** [fennb/phirehose#104]
The class `Oauthphirehose` has `@interal` docblock. Nevertheless this is the class I normally need to extend, to pass in the `consumerKey` and `consumerSecret`, right?

**Comment by DarrenCook** [comment]
@internal is used for comments only of interest to developers modifying that code (rather than something to be exported to the public API docs). That javadoc tag is *not* labelling the class.

https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.internal.pkg.html
