### ISSUE TITLE
Still having issue with connections

### ISSUE THREAD

**Issue by blakdronzer** [fennb/phirehose#111]
I have the environment set to php 7.1.2 and have the openssl configured correctly and it shows up as enabled module too. Bur when i try running the stuff in command line, it shows TCP Failure .. but no issue as such is understood as why?

Phirehose: Connecting to twitter stream: https://stream.twitter.com/1.1/statuses/filter.json with params: array (  'track' => 'V Vaidyanathan,capital first,v. vaidyanathan,v.vaidyanathan,vaidyanathan,vaidyanathan19',)
Phirehose: Connecting to ssl://stream.twitter.com, port=443, connectTimeout=5
Phirehose: TCP failure 1 of 20 connecting to stream:  (0). Sleeping for 1 seconds.
Phirehose: Connecting to twitter stream: https://stream.twitter.com/1.1/statuses/filter.json with params: array (  'track' => 'V Vaidyanathan,capital first,v. vaidyanathan,v.vaidyanathan,vaidyanathan,vaidyanathan19',)
Phirehose: Connecting to ssl://stream.twitter.com, port=443, connectTimeout=5
Phirehose: TCP failure 2 of 20 connecting to stream:  (0). Sleeping for 2 seconds.
Phirehose: Connecting to twitter stream: https://stream.twitter.com/1.1/statuses/filter.json with params: array (  'track' => 'V Vaidyanathan,capital first,v. vaidyanathan,v.vaidyanathan,vaidyanathan,vaidyanathan19',)
Phirehose: Connecting to ssl://stream.twitter.com, port=443, connectTimeout=5
Phirehose: TCP failure 3 of 20 connecting to stream:  (0). Sleeping for 4 seconds.
cPhirehose: Connecting to twitter stream: https://stream.twitter.com/1.1/statuses/filter.json with params: array (  'track' => 'V Vaidyanathan,capital first,v. vaidyanathan,v.vaidyanathan,vaidyanathan,vaidyanathan19',)

Please note - i am currently working the stuff on localhost - for developmental purpose. And it is failing to connect and cant get any reason as why :(
Need help on resolving the same.

**Comment by ficosta** [comment]
Maybe you have this same problem:
https://github.com/fennb/phirehose/issues/70#issuecomment-56686773

**Comment by nabilashahid** [comment]
@blakdronzer Please update if you were able to figure out a solution to this
