### ISSUE TITLE
update keywords (tags) while connected

### ISSUE THREAD

**Issue by HashmatWaziri** [fennb/phirehose#114]
how can we do the following : to change the keyword inside setTrack() without disconnecting the twitter streaming api. and then the streaming api should search the new tags.

**Comment by JPeterson2015** [comment]
I am also wondering how this can be done? I'm pulling my keywords in from a database and that database can change frequently.

Anyone else know the answer to this?

**Comment by fennb** [comment]
I don't believe this is possible. Tags are set on a per connection basis, so you have to disconnect/reconnect.

I would recommend doing this periodically (maybe every 5 minutes or so), as otherwise you'll hit connection rate limits and your account will be banned.
