### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by subbe** [fennb/phirehose#115]
throws this error on laravel 5.4 (php >= 7.0.0)

`count(): Parameter must be an array or an object that implements Countable {"exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /vendor/fennb/phirehose/lib/Phirehose.php:609)`

**Comment by DevDavido** [comment]
Fixed in #113
