### ISSUE TITLE
Tag a new Release for PHP 7.2 support

### ISSUE THREAD

**Issue by stefanzweifel** [fennb/phirehose#118]
Hi there,

With #113 this project has received PHP 7.2 support. The `dev-master` version of this package would work on PHP 7.2, but there's currently no tagged version that works. Therefore other packages which depend on `phirehose` don't work (for example [spatie/twitter-streaming-api](https://github.com/spatie/twitter-streaming-api)).

Would it be possible to create a new release for this package? I would suggest creating a new PATCH release `v1.0.2` as the changes made in #113 don't add new features or break anything. Creating and pushing a tag in git should be enough.

Thank you.

**Comment by jonathantullett** [comment]
Seconded - please create a tagged release for this.

**Comment by L3o-pold** [comment]
@fennb Could you create a release please?

**Comment by yazeed** [comment]
Please create a release, thank you.

**Comment by sudofox** [comment]
Was this ever done?

**Comment by jonathantullett** [comment]
I didn't see one, and was recently looking for a php8 release too, but the code as-is throws up errors when running under php8 due to methods having optional arguments before mandatory arguments.

**Comment by sudofox** [comment]
I had to use dev-master to get my stuff to work.

**Comment by fennb** [comment]
Apologies, the mails from this repo were getting auto-filtered away somewhere unexpected and I hadn't seen the discussion on this.

https://github.com/fennb/phirehose/releases/tag/v1.0.2 is a go!
