### ISSUE TITLE
fputs bug in ghetto collection?

### ISSUE THREAD

**Issue by sledmonkey** [fennb/phirehose#53]
I ran into an issue yesterday where I could no longer process the txt files from ghetto-queue-collect with ghetto-queue-consume.  In my case it looks like for whatever reason each status tweet was being appended to the file without adding a new line.  Subsequently when trying to process, line 91 of the consume script (while ($rawStatus = fgets($fp, 8192))) was pulling data chunks that contained multiple status tweets which resulted in incomplete json arrays causing the script to break.  

The short term fix I made was to change the collector to add PHP_EOL to each status save(line 70):
fputs($this->getStream(), $status . PHP_EOL);

What I'm wondering is if anyone else has had this problem and second, would this be better to move into Phirehose.php where enqueueStatus is called?

**Comment by fennb** [comment]
Fixed in 197b7da3d0b63f2de972fb2a14c838feb4f304dc
