### ISSUE TITLE
Problem streaming Twitter Timeline

### ISSUE THREAD

**Issue by tatepoter** [fennb/phirehose#59]
Hi, we have an application based on the Twitter API, but since the 14/01/14 we are experiencing problems due to upgrade of their API. Specifically we are using Phirehose Framework to retrieve Streams of certain users. However, we could not retrieve tweets as before that date. Randomly we recover certain tweets but not constantly. The error that we find to connect with Twitter is as follows:
04/03 19:51:09 - Consume rate: 1 status/sec (55 total), avg enqueueStatus(): 0.24ms, avg checkFilterPredicates(): 0ms (10 total) over 62 seconds, max stream idle period: 5 seconds.
04/03 19:52:11 - Consume rate: 1 status/sec (41 total), avg enqueueStatus(): 0.17ms, avg checkFilterPredicates(): 0ms (11 total) over 62 seconds, max stream idle period: 5 seconds.
04/03 19:53:11 - Consume rate: 1 status/sec (51 total), avg enqueueStatus(): 11.93ms, avg checkFilterPredicates(): 0ms (10 total) over 60 seconds, max stream idle period: 5 seconds.
04/03 19:54:11 - Consume rate: 1 status/sec (51 total), avg enqueueStatus(): 8.2ms, avg checkFilterPredicates(): 0ms (10 total) over 60 seconds, max stream idle period: 4 seconds.
04/03 19:55:12 - Consume rate: 1 status/sec (59 total), avg enqueueStatus(): 2.04ms, avg checkFilterPredicates(): 0ms (12 total) over 61 seconds, max stream idle period: 5 seconds.
04/03 19:56:12 - Consume rate: 1 status/sec (49 total), avg enqueueStatus(): 0.09ms, avg checkFilterPredicates(): 0ms (12 total) over 60 seconds, max stream idle period: 4 seconds.
04/03 19:57:12 - Consume rate: 1 status/sec (59 total), avg enqueueStatus(): 2.67ms, avg checkFilterPredicates(): 0ms (11 total) over 60 seconds, max stream idle period: 4 seconds.
04/03 19:58:12 - Consume rate: 1 status/sec (56 total), avg enqueueStatus(): 0.1ms, avg checkFilterPredicates(): 0ms (11 total) over 60 seconds, max stream idle period: 5 seconds.
04/03 19:59:12 - Consume rate: 1 status/sec (54 total), avg enqueueStatus(): 0.09ms, avg checkFilterPredicates(): 0ms (10 total) over 60 seconds, max stream idle period: 5 seconds.
04/03 20:00:01 - Connecting to twitter stream: https://stream.twitter.com/1.1/statuses/filter.json with params: array ( 'follow' => '781293,807095,1169241,1652541,4157261,4898091,7520262,7556392,7557352,8354962,9825392,9974322,...,)
04/03 20:00:01 - Resolved host stream.twitter.com to 199.16.156.20, 199.16.156.110
04/03 20:00:01 - Connecting to ssl://199.16.156.20, port=443, connectTimeout=5
04/03 20:00:02 - Connection established to 199.16.156.20
04/03 20:00:02 - POST /1.1/statuses/filter.json HTTP/1.1
Host: stream.twitter.com:443
Connection: Close
Content-type: application/x-www-form-urlencoded
Content-length: 2825
Accept: /
Authorization: OAuth realm="",oauth_consumer_key="xxxxxxxxxxxxxxxxxx",oauth_nonce="12a852fc6ca90588971d7eab192aa709",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1393959602",oauth_version="1.0A",oauth_token="xxxxxxxxxxxxxxx15-wxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",oauth_signature="powpMeuX2bL99ORYfE9FIhyBUyg%3D"
User-Agent: Phirehose/1.0RC +https://github.com/fennb/phirehose

Please we need your help to resolve this issue.
Thanks in advance

**Comment by fennb** [comment]
Should be fixed by 197b7da3d0b63f2de972fb2a14c838feb4f304dc - closing until further notice.
