### ISSUE TITLE
Doesn't detect authorization failures. Just enters an infinite loop trying to authorize with wrong credentials

### ISSUE THREAD

**Issue by HongKilDong** [fennb/phirehose#77]
I made a mistake entering my twitter credentials but instead of throwing exception, filter-oauth.php example entered an infinite loop trying to authorize with wrong credentials and getting:

```
HTTP/1.1 401 Authorization Required
cache-control: must-revalidate,no-cache,no-store
connection: close
content-length: 266
content-type: text/html
date: Tue, 03 Feb 2015 16:51:53 UTC
server: tsa
www-authenticate: OAuth realm="Firehose"
x-connection-hash: 870557403e3c5879d660975bc7e5d976

<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
</head>
<body>
<h2>HTTP ERROR: 401</h2>
<p>Problem accessing '/1.1/statuses/filter.json'. Reason:
<pre>    Unauthorized</pre>
</body>
</html>
```

**Comment by j0an** [comment]
Did you solve this? I'm in a similar problem :(

**Comment by fennb** [comment]
@j0an The solution to the error is ensuring you have correct credentials.

The bug itself is the fact that the script ends up in a loop (rather than exiting). 

If you enter the correct credentials, you should be able to connect successfully.
