### ISSUE TITLE
Feature request: Make it work with ReactPHP

### ISSUE THREAD

**Issue by stevecoug** [fennb/phirehose#79]
https://github.com/reactphp/
http://reactphp.org/

ReactPHP provides a framework for asynchronous event-driven PHP programming. This would allow a script to do more than just parse tweets. It would also move a lot of the logic out of Phirehose, allowing it to be more lean and easy to understand and modify.

I'd be willing to help with this effort if you think it'd be a good direction to go.

**Comment by compwright** [comment]
Phirehose is a stand-alone library, so we'd rather avoid large dependencies (any dependencies, really), so this would be better as a separate project. It could certainly be based on Phirehose, and I think we would be happy to link to it as a related project or alternate approach.
