### ISSUE TITLE
processQueueFile function in ghetto-queue-consume never go into decode line

### ISSUE THREAD

**Issue by blaxroze** [fennb/phirehose#87]
I found out in log that <b>processQueueFile</b> function never decode the tweet if there is more than 1 tweet.
Is this because of the tweets in current file not separated with coma?
or raw statuses json format is not valid.
I want to insert each tweet into my database.

<pre>
$data = json_decode($rawStatus, true);
if (isset($data) && isset($data['user']['screen_name'])) {
        $this->log('Decoded tweet: ' . $data['user']['screen_name'] . ': ' . urldecode($data['text']));
}
</pre>

**Comment by laoman** [comment]
Hey @blaxroze search for issue "fputs bug in ghetto collection? #53" the answer lies there

**Comment by blaxroze** [comment]
@laoman Yup thanks. I found out the answer too.

**Comment by laoman** [comment]
@blaxroze you might be interested about this #96

**Comment by fennb** [comment]
Would anyone kind like to submit a pull request to change ghetto-queue-collect to append newlines as per #53? You would close 3 issues and be considered a genuine hero :)

**Comment by laoman** [comment]
@fennb just submitted one

**Comment by fennb** [comment]
Fixed in 197b7da3d0b63f2de972fb2a14c838feb4f304dc
