### ISSUE TITLE
Warning during execution. 

### ISSUE THREAD

**Issue by adeelyaqoob** [fennb/phirehose#95]
why i am getting this using Phirehose for streaming twitter data??
Warning:  stream_select() [function.stream-select]: unable to select [4]: Interrupted system call (max_fd=4)

**Comment by DarrenCook** [comment]
I suspect the `max_fd=4` is telling you that you script already has 4 open file handles and is not allowed any more. (I'm guessing.)
If you give some more details about your setup (OS, OS kernel version, available memory, etc) someone might be able to suggest something to try.
