### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by luismldias** [fennb/phirehose#99]
Hello,

We have been using phirehose for Twitter stream consumptions for a while now and it has been working fine.

Suddenly and without any update to the the code it stopped working. The stream does not start and it fails silently without any exception being raised. 

I have checked all the app tokens and secrets and everything seems fine when calling the twitter api from curl.

My question is, are there any phirehose log files that i can check to try and see what is wrong? I have been looking but so far i haven't found any.

Can you please provide some help?

Thanks in advance,

Luis Dias

**Comment by DarrenCook** [comment]
> Suddenly and without any update to the the code it stopped working. The stream 
> does not start and it fails silently without any exception being raised.
> 
> I have checked all the app tokens and secrets and everything seems fine when 
> calling the twitter api from curl.

Any chance that PHP got upgraded? (If so, make sure you are using the
latest github version of Phirehose.)

> My question is, are there any phirehose log files that i can check to try and 
> see what is wrong? I have been looking but so far i haven't found any.

Check the php error log; socket or DNS errors would be written there, IIRC.

Darren

**Comment by luismldias** [comment]
Hi,

Thanks for the reply.

PHP has not been upgraded.

I have tried finding the logs you mentioned but no luck...**sigh**

Seems like i am chasing a ghost here

**Comment by DarrenCook** [comment]
> PHP has not been upgraded.

Can you report your PHP version. (php -v)

> I have tried finding the logs you mentioned but no luck...*sigh*

It must exist somewhere. From the commandline, try:

  php -i | grep -i (error|log)

to track down any related settings.

Darren

**Comment by luismldias** [comment]
Hi Darren,

Thanks for the reply.

PHP version is PHP 5.4.4-14+deb7u14 (cli) (built: Aug 21 2014 08:36:44) 

I'll check the ini settings for the error log location

**Comment by compwright** [comment]
Could this be related to #78?
